#!/usr/bin/env bun
/**
 * embed-plugin.ts
 *
 * Reads the compiled opencode-plugin bundle from
 * ../plugin/dist/signet.mjs and embeds it as a string literal
 * inside src/plugin-bundle.ts. Run before bundling src/index.ts so the
 * plugin travels with the connector without a separate file.
 *
 * If the plugin package has not been built yet, the script exits cleanly
 * and leaves the placeholder in place (install() will write an empty file,
 * which OpenCode ignores).
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const packageRoot = join(__dirname, "..");
const pluginDistPath = join(packageRoot, "..", "plugin", "dist", "signet.mjs");
const bundleSourcePath = join(packageRoot, "src", "plugin-bundle.ts");

if (!existsSync(pluginDistPath)) {
	console.warn(`[embed-plugin] Plugin bundle not found at ${pluginDistPath} — skipping embed`);
	process.exit(0);
}

const pluginSource = readFileSync(pluginDistPath, "utf-8");

// Escape backticks and template literal markers in the plugin source
const escaped = pluginSource.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const output = `/**
 * Bundled OpenCode plugin content
 *
 * Auto-generated by scripts/embed-plugin.ts — do not edit manually.
 * Re-run the build to regenerate from ../plugin/dist/signet.mjs
 */

export const PLUGIN_BUNDLE = \`${escaped}\`;
`;

writeFileSync(bundleSourcePath, output);
console.log(`[embed-plugin] Embedded ${pluginDistPath} → src/plugin-bundle.ts`);
