#!/usr/bin/env bun
/**
 * embed-extension.ts
 *
 * Reads the compiled pi extension bundle from
 * ../extension/dist/signet-pi.mjs and embeds it as a string
 * literal inside src/extension-bundle.ts. Run before bundling src/index.ts so
 * the connector ships the managed extension without a runtime dependency on
 * @signet/pi-extension.
 *
 * If the extension package has not been built yet, the script exits cleanly
 * and leaves the placeholder in place. install() will then fail with a clear
 * message instead of writing an empty managed extension file.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const packageRoot = join(__dirname, "..");
const extensionDistPath = join(packageRoot, "..", "extension", "dist", "signet-pi.mjs");
const bundleSourcePath = join(packageRoot, "src", "extension-bundle.ts");

if (!existsSync(extensionDistPath)) {
	throw new Error(
		`[embed-extension] Extension bundle not found at ${extensionDistPath}. Build @signet/pi-extension first so the connector cannot publish a stale or empty embedded bundle.`,
	);
}

const extensionSource = readFileSync(extensionDistPath, "utf-8");
const escaped = extensionSource.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const output = `/**
 * Bundled pi extension content
 *
 * Auto-generated by scripts/embed-extension.ts — do not edit manually.
 * Re-run the build to regenerate from ../extension/dist/signet-pi.mjs
 */

export const EXTENSION_BUNDLE = \`${escaped}\`;
`;

writeFileSync(bundleSourcePath, output);
console.log(`[embed-extension] Embedded ${extensionDistPath} → src/extension-bundle.ts`);
