-- Migration 021: Structural checkpoint snapshot fields
--
-- Adds optional structural snapshot columns to session_checkpoints so
-- recovery can prioritize focal entities, active aspects, and traversal
-- metadata from the prior session.

-- Columns added programmatically in migrations.rs:
--   session_checkpoints.focal_entity_ids TEXT
--   session_checkpoints.focal_entity_names TEXT
--   session_checkpoints.active_aspect_ids TEXT
--   session_checkpoints.surfaced_constraint_count INTEGER
--   session_checkpoints.traversal_memory_count INTEGER
